---
soa_domain_name: soa_int
soa_domain_home: "{{ oracle_config }}/soa_int"
soa_admin_port: 8101
soa_ms_port: 8102
soa_wsm_port: 8103
soa_ms_group: soa_int_ms
soa_wsm_group: soa_int_wsm
soa_db_user: INT_SOAINFRA
soa_db_service: "{{ soa_db_service_int }}"
wlst_script_dir: "{{ oracle_stage }}/wlst"
soa_domain_script: "{{ wlst_script_dir }}/create-soa-int-domain.py"
