---
- name: Restart OHS
  ansible.builtin.systemd:
    name: "{{ ohs_service_name }}"
    state: restarted
  become: true

- name: Reload systemd
  ansible.builtin.systemd:
    daemon_reload: true
  become: true
