---
soa_domain_name: soa_sgg
soa_domain_home: "{{ oracle_config }}/soa_sgg"
soa_admin_port: 8401
soa_ms_port: 8402
soa_wsm_port: 8403
soa_ms_group: soa_sgg_ms
soa_wsm_group: soa_sgg_wsm
soa_db_user: SGG_SOAINFRA
soa_db_service: "{{ soa_db_service_sgg }}"
wlst_script_dir: "{{ oracle_stage }}/wlst"
soa_domain_script: "{{ wlst_script_dir }}/create-soa-sgg-domain.py"
